name: Generate Snake Game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 */12 * * *"  # A cada 12 horas
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Criar ou trocar para a branch output
        run: |
          git fetch origin output || git checkout -b output
          git checkout output

      - name: Gerar Snake Game
        uses: Platane/snk/svg-only@v3
        with: 
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark&color_snake=blue

      - name: Commit substituindo o anterior
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add github-snake.svg github-snake-dark.svg
          git commit --amend -m "Atualizar Snake Game SVG"
          git push origin output --force
